alias g='git'
alias ga='git add'
alias gaa='git add .'
alias gap='git add -p'
alias gb='git branch'
alias gbd='git branch -D'
alias gch='git checkout'
alias gcb='git checkout -b'
alias gc='git commit'
alias gca='git add -A $(git root) && git commit'
alias gcm='git commit -m'
alias gcam='git add -A $(git root) && git commit -m'
alias gco='git commit --amend --no-edit'
alias gd='git diff'
alias gds='git diff --staged'
alias gf='git fetch -p'
alias gl='git log --pretty=format:"%Cred%h%Creset - %s%C(yellow)%d%Creset" --graph --abbrev-commit -n 15 --branches'
alias gm='git merge'
alias gms='git merge --ff --squash'
alias gs='git status'
alias gss='git stash save'
alias gsp='git stash pop'
alias gp='git push'
alias gpl='git pull'
alias grb='git rebase'
alias grbi='git rebase -i'
alias gr='git reset'
alias grs='git reset --soft'
alias grh='git reset --hard'

alias b='bundle'
alias be='bundle exec'

mkcd() {
  mkdir -p $@ && cd $@;
}